# Generated by Django 3.0.3 on 2020-03-04 03:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200302_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
