# Generated by Django 3.0.4 on 2020-03-15 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200312_2308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
